### PR TITLE
Separate interfaces for BLAKE2b in keyed and non-keyed mode

### PR DESCRIPTION
**Pull request by brycx**
see #208 

TODO:
 - [ ] Update fuzzing targets

NOTE: The duplication of testing code from `StreamingContextConsistencyTester` in `mac::blake2b` should not be redundant, since it tests using different secret key and sizes.

### CODE REVIEW

**Comment by brycx** [comment]
@vlmutolo The only question that remains from my side on this change is whether to re-export `Tag` from `hazardous` as we do in `orion::hash` with `Digest`? We could avoid having another newtype conversion, but the current high-level sets a strict limit for the size that can be expected from the `Digest` (instead of the `1..=64` range in `hazardous`). What do you think?

**Review by vlmutolo — APPROVED** [review]
These changes seem like they're good to go. Only small comment would be one of documentation. Maybe there should be a line added to the top of the high-level hash documentation that says something like:

> If you're looking for a keyed hash, see the `mac` module.

**Comment by vlmutolo** [comment]
@brycx I don't think it would be a big issue to re-export `Tag`. The high-level module's `authenticate` and `authenticate_verify` functions still return a `Tag` with a set length that the user can't modify. So long as the user sticks with those functions from the module — and I don't see an obvious way around using them — then the user will be fine, no?

I'm trying to think of a situation where someone would want to generate their own `Tag` from a slice and then somehow use it to authenticate something, but I can't come up with anything realistic. I think it's fine to re-export.

**Comment by brycx** [comment]
> So long as the user sticks with those functions from the module — and I don't see an obvious way around using them — then the user will be fine, no?

I agree. It was simply the tighter restrictions on the newtype that maybe could've made sense. But I couldn't think of a convincing argument.

> I'm trying to think of a situation where someone would want to generate their own Tag from a slice and then somehow use it to authenticate something, but I can't come up with anything realistic. I think it's fine to re-export.

Indeed. The underlying `secure_cmp()` would fail either way, if the `expected` had a longer or shorter tag than 32 bytes. I've added another error condition to the docs, and a check in the `authenticate_verify` function for clarity on this expectation.

**Pull request merged**
